require("dotenv").config();
const mongoose = require("mongoose");
const Aircraft = require("./models/Aircraft");

async function seedAircrafts() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ MongoDB Atlas connected");

    await Aircraft.deleteMany();

    await Aircraft.insertMany([
    {
    "name": "Cessna 172S Skyhawk",
    "image": "https://aviationinteractivelearningplatform.netlify.app/images/aircrafts/Cessna_172S.png",
    "description": "The Cessna 172S Skyhawk is one of the most widely used single-engine, high-wing aircraft in the world and is considered the benchmark for flight training and general aviation. Introduced as an evolution of earlier Skyhawk models, the 172S features a fuel-injected Lycoming IO-360-L2A engine producing 180 horsepower, offering improved climb performance and reliability compared to carbureted variants. Its high-wing configuration provides excellent downward visibility and inherent stability, making it ideal for student pilots, private owners, and flight schools. The aircraft typically seats four occupants and is capable of cruising at approximately 122 knots with a range of around 640 nautical miles. The 172S is known for its forgiving flight characteristics, strong safety record, and low operating costs. Modern versions are equipped with the Garmin G1000 glass cockpit, integrating flight instruments, navigation, and engine monitoring into a digital display system. The fixed tricycle landing gear and robust airframe allow operations from paved and semi-prepared runways. Overall, the Cessna 172S remains a reliable, economical, and versatile aircraft, widely respected for training, cross-country flying, and recreational aviation.",
    "parts": [
      {
        "name": "Cockpit",
        "description": "The cockpit of the Cessna 172S is the primary control center of the aircraft, designed for simplicity, visibility, and ease of operation. It accommodates the pilot and co-pilot in a side-by-side seating arrangement, which is ideal for flight training and instruction. All primary flight controls, including the control yoke, rudder pedals, throttle, mixture, and flap controls, are ergonomically positioned to reduce pilot workload. The cockpit provides excellent forward and side visibility, which is essential during takeoff, landing, and visual navigation. Instrument panels typically include either analog gauges or a glass cockpit, but structurally the cockpit houses flight instruments, circuit breakers, and control linkages. The cockpit structure is reinforced to protect occupants and support instrument mounting while remaining lightweight."
      },
      {
        "name": "Fuselage",
        "description": "The fuselage of the Cessna 172S is the central body of the aircraft and serves as the main structural backbone. Constructed primarily from aluminum alloy, it is designed to be lightweight yet strong enough to withstand aerodynamic loads, internal stresses, and landing forces. The fuselage houses the cockpit, passenger cabin, baggage compartment, and attachment points for wings, landing gear, and tail assembly. Its semi-monocoque construction distributes loads efficiently across frames, stringers, and skin panels. The fuselage also provides protection to occupants and supports internal systems such as control cables, electrical wiring, and fuel lines. Aerodynamically, the fuselage is shaped to minimize drag while maintaining structural integrity. The fuselage is essential for maintaining aircraft balance, strength, and overall stability during flight."
      },
      {
        "name": "Wings",
        "description": "The wings of the Cessna 172S are high-mounted and are the primary lift-producing components of the aircraft. Their high-wing configuration enhances stability and provides better ground clearance and downward visibility. Constructed from aluminum alloy, the wings are supported by wing struts that transfer aerodynamic loads to the fuselage. Each wing contains fuel tanks integrated into the structure, improving balance and simplifying fuel management. The wings house control surfaces such as ailerons and flaps, which are essential for roll control and lift enhancement during takeoff and landing. Aerodynamically shaped airfoils allow the aircraft to generate lift efficiently at low speeds, which is ideal for training operations. The wing design contributes significantly to the aircraft’s forgiving handling characteristics, making stalls and slow-speed flight more predictable and safe."
      },
      {
        "name": "Empennage (Tail Section)",
        "description": "The empennage of the Cessna 172S consists of the horizontal stabilizer, vertical stabilizer, elevator, and rudder. This tail section provides stability and control in pitch and yaw axes. The horizontal stabilizer balances the aircraft longitudinally, while the elevator allows the pilot to control pitch attitude. The vertical stabilizer maintains directional stability, and the rudder enables yaw control, especially during turns and crosswind landings. The empennage is constructed from lightweight aluminum and is aerodynamically designed to maintain smooth airflow. It plays a vital role in keeping the aircraft stable and controllable throughout all phases of flight. Without an effective empennage, controlled flight would not be possible."
      },
      {
        "name": "Landing Gear",
        "description": "The Cessna 172S uses a fixed tricycle landing gear configuration, consisting of two main wheels and a nose wheel. This design provides excellent ground stability and makes the aircraft easy to taxi, take off, and land. The main landing gear absorbs landing loads, while the nose wheel allows steering control on the ground. The fixed design reduces mechanical complexity and maintenance requirements. Structurally, the landing gear is attached to reinforced points on the fuselage, allowing it to withstand repeated training landings. It ensures safe ground operations and protects the airframe from excessive stress."
      },
      {
        "name": "Powerplant Installation",
        "description": "The powerplant installation of the Cessna 172S Skyhawk includes the engine mounting structure, engine cowling, and propeller attachment system. The piston engine is mounted on a reinforced firewall at the front of the fuselage, which safely transfers thrust and vibration loads into the airframe. A tubular steel engine mount provides structural strength and vibration damping. The cowling surrounds the engine and is aerodynamically shaped to reduce drag while directing airflow for effective engine cooling. Cooling inlets and outlets maintain proper operating temperatures during all flight phases. The propeller is securely attached to the engine crankshaft, converting engine power into thrust. This installation ensures engine stability, efficient power transmission, and safe, reliable aircraft operation."
      }
    ]
  },
  {
    "name": "Tecnam P‑Mentor",
    "image": "https://aviationinteractivelearningplatform.netlify.app/images/aircrafts/Tecnam-P-Mentor.png",
    "description": "The Tecnam P-Mentor is a modern two-seat training aircraft developed to meet the needs of contemporary flight schools and military pilot training programs. Designed with efficiency, safety, and cost-effectiveness in mind, the P-Mentor features a low-wing configuration and tandem seating, closely resembling the layout of advanced military trainers. It is powered by a reliable piston engine, optimized for both visual flight rules (VFR) and instrument flight rules (IFR) training. The aircraft incorporates advanced aerodynamics and lightweight composite materials, resulting in excellent handling characteristics and fuel efficiency. The P-Mentor supports aerobatic training within defined limits, allowing student pilots to gain experience in upset recovery and advanced maneuvers. Its modern glass cockpit avionics provide digital flight displays, navigation, and training-oriented systems such as data recording for post-flight analysis. With low operating and maintenance costs, the Tecnam P-Mentor is well-suited for high-utilization training environments. The aircraft bridges the gap between basic trainers and high-performance aircraft, preparing pilots for more complex platforms while maintaining safety and reliability.",
    "parts": [
      {
        "name": "Cockpit",
        "description": "The cockpit of the Tecnam P-Mentor is designed for student training and pilot instruction. It features a tandem seating arrangement, with the student in the front and the instructor behind, allowing for clear oversight during flight. All primary flight controls, including the control stick, rudder pedals, throttle, and flap lever, are ergonomically positioned for accessibility and proper pilot technique. The cockpit provides excellent forward and side visibility, which is crucial during takeoff, landing, and visual navigation exercises. It also houses essential instruments and displays for flight monitoring, navigation, and engine performance. The canopy design allows for good ventilation and provides structural support while protecting occupants. The cockpit structure is reinforced to absorb minor impacts and supports integrated avionics systems safely. Overall, it is a critical part of the aircraft, providing both control interface and pilot safety in training scenarios."
      },
      {
        "name": "Fuselage",
        "description": "The fuselage of the Tecnam P-Mentor serves as the central structural backbone, connecting all major components such as wings, tail, landing gear, and engine mounts. Constructed primarily from lightweight aluminum and composite materials, the fuselage ensures a strong yet aerodynamic form, reducing drag while maintaining structural integrity. It houses the cockpit, passenger areas, and internal systems such as control cables, electrical wiring, and avionics wiring harnesses. The fuselage’s semi-monocoque design allows it to efficiently distribute aerodynamic and landing loads across the skin, frames, and stringers. It is reinforced to withstand the stresses of repeated training operations, including multiple takeoffs and landings. Additionally, it contributes to overall aircraft stability, handling, and weight distribution. The fuselage is a critical component for safety, structural strength, and proper aerodynamics."
      },
      {
        "name": "Wings",
        "description": "The Tecnam P-Mentor features low-mounted wings designed for training efficiency, stability, and maneuverability. Constructed from aluminum and composite materials, the wings provide lift, house the fuel tanks, and integrate key control surfaces such as ailerons and flaps. The ailerons allow roll control, while flaps increase lift and drag during takeoff and landing, permitting slower approach speeds and shorter runway operations. The wing design contributes to balanced flight characteristics and helps new pilots learn coordinated control inputs safely. Struts or internal spars provide structural reinforcement, distributing aerodynamic loads to the fuselage efficiently. Aerodynamic shaping reduces drag and improves performance, making the aircraft fuel-efficient and stable under varying flight conditions. The wings are essential for flight, lift generation, and overall safety."
      },
      {
        "name": "Empennage (Tail Section)",
        "description": "The empennage of the Tecnam P-Mentor includes the horizontal stabilizer, elevator, vertical stabilizer, and rudder, providing longitudinal and directional stability. The horizontal stabilizer keeps the aircraft balanced along the pitch axis, while the elevator allows pitch control. The vertical stabilizer provides directional stability, and the rudder enables yaw control during turns and crosswind landings. Constructed from lightweight aluminum and composite materials, the tail section is aerodynamically shaped for efficient airflow. Control surfaces are connected to the cockpit controls via cables or rods, allowing smooth and responsive handling. The empennage is crucial for maintaining stability and control, especially during maneuvers and training exercises."
      },
      {
        "name": "Powerplant Installation (Engine Mount)",
        "description": "The Tecnam P-Mentor engine is mounted at the front of the fuselage on a reinforced firewall structure. The engine installation includes the cowling, propeller mounting, and cooling airflow channels. This structure ensures that the engine remains securely attached while efficiently transferring thrust to propel the aircraft. It also minimizes vibrations, ensures proper cooling, and protects the cockpit and fuselage from heat and fire hazards. The design allows easy access for maintenance while supporting the smooth operation of the engine during training flights. The powerplant installation is essential for safe, reliable, and efficient propulsion."
      },
      {
        "name": "Landing Gear",
        "description": "The landing gear of the Tecnam P-Mentor is a fixed tricycle configuration, including two main wheels and a steerable nose wheel. Designed for frequent takeoffs and landings, it absorbs impact forces efficiently and provides stable ground handling. Shock-absorbing struts reduce stress on the airframe, while the nose wheel allows precise steering during taxiing. The landing gear attachment points are reinforced to handle repeated landings during flight training. Its design ensures safe operations on both paved and semi-prepared runways, which is ideal for flight schools. The landing gear is critical for ground stability, safe takeoffs, and landings."
      }
    ]
  },
  {
    "name": "Diamond DA62",
    "image": "https://aviationinteractivelearningplatform.netlify.app/images/aircrafts/DA62.png",
    "description": "TThe Diamond DA62 is a modern, twin-engine, multi-purpose aircraft designed for efficiency, safety, and comfort. Built primarily from advanced composite materials, the DA62 features a sleek aerodynamic profile that reduces drag and improves fuel efficiency. It is powered by two Austro Engine AE330 turbocharged diesel engines, which burn Jet-A fuel, offering lower operating costs and global fuel availability. The aircraft can seat up to seven occupants, making it suitable for personal transport, business travel, and surveillance missions. The DA62 cruises at approximately 190 knots and offers excellent range and endurance. A standout feature is its exceptional safety record, supported by redundant systems, excellent single-engine performance, and benign handling characteristics. The Garmin G1000 NXi avionics suite provides advanced navigation, weather, traffic awareness, and engine monitoring. Large windows and a quiet cabin enhance passenger comfort and visibility. Overall, the Diamond DA62 represents a balance of performance, economy, and modern technology in the light twin-engine category.",
    "parts": [
      {
        "name": "Cockpit",
        "description": "TThe cockpit of the Diamond DA62 is designed for dual-pilot operation and passenger comfort. It features a side-by-side seating arrangement for the pilot and co-pilot, with ergonomically positioned controls for easy access during flight. The cockpit includes full flight controls, throttle quadrants, rudder pedals, and flap controls, providing complete command of the aircraft. It is equipped with a modern Garmin G1000 NXi glass cockpit, displaying flight, navigation, engine, and system data in an integrated format. Visibility is excellent in all directions due to the large canopy and windows, essential for navigation, takeoff, and landing. The cockpit also includes climate control, noise insulation, and safety features such as energy-absorbing seats and reinforced structures. It serves as the central hub for both control and situational awareness, allowing pilots to operate the aircraft safely and efficiently, while also providing the space and systems needed for long-range operations and advanced training."
      },
      {
        "name": "Fuselage",
        "description": "The fuselage of the Diamond DA62 is a composite structure primarily made from carbon-fiber reinforced polymer, which offers high strength-to-weight ratio and excellent corrosion resistance. It houses the cockpit, passenger cabin, baggage compartments, and internal systems like wiring and control linkages. The fuselage connects the wings, empennage, landing gear, and engine nacelles, acting as the main structural backbone of the aircraft. Its design ensures aerodynamic efficiency, with smooth surfaces reducing drag for better fuel economy and cruise performance. The semi-monocoque structure distributes aerodynamic and landing loads evenly across the skin and internal frames, providing durability and structural integrity. Reinforced areas handle stresses from takeoff, landing, and turbulence. The fuselage also contributes to passenger comfort with spacious seating, climate control ducting, and reduced vibration levels. It is critical for overall aircraft balance, structural strength, and safe operation."
      },
      {
        "name": "Wings",
        "description": "The wings of the Diamond DA62 are low-mounted and constructed from carbon-fiber composite materials for strength and lightweight efficiency. They are designed to provide lift while housing fuel tanks, ailerons, and flaps. The ailerons control roll, while the flaps adjust lift and drag during takeoff and landing for shorter runway operations. The wings are equipped with winglets that improve aerodynamic efficiency, reduce drag, and enhance range. Internal spars and ribs distribute loads evenly to the fuselage. The design allows smooth airflow over the wing surface, reducing turbulence and increasing cruise performance. The wings also contribute to stability and handling characteristics, making the aircraft predictable and safe during training, long-distance flights, and single-engine operations. Overall, the wing structure is essential for flight, lift generation, and aerodynamic efficiency."
      },
      {
        "name": "Empennage (Tail Section)",
        "description": "The empennage of the DA62 includes the horizontal stabilizer, elevator, vertical stabilizer, and rudder, providing essential pitch and yaw control. The horizontal stabilizer maintains longitudinal balance, while the elevator adjusts pitch for climbs, descents, and trimming. The vertical stabilizer provides directional stability, and the rudder controls yaw during turns and crosswind operations. Constructed from composite materials, the empennage is lightweight yet strong, aerodynamically shaped to ensure smooth airflow and effective control. Control surfaces are connected to cockpit inputs via cables or rods, offering precise and predictable responses. The tail section is crucial for stability, balance, and safe handling, especially during single-engine flight, turbulence, or emergency maneuvers. It also contributes to aerodynamic efficiency by minimizing drag while maximizing stability."
      },
      {
        "name": "Landing Gear",
        "description": "The DA62 uses a retractable tricycle landing gear system, consisting of two main gear wheels and a steerable nose wheel. Retracting the landing gear reduces drag during flight and improves cruise efficiency. The main landing gear absorbs loads during landings and supports the aircraft’s weight on the ground, while the nose wheel provides steering control for taxi operations. Shock-absorbing struts reduce impact forces, protecting the fuselage and providing comfort. The gear is designed to handle frequent operations and is reinforced to manage stress from training, private, and commercial flights. Retractable mechanisms are controlled by the cockpit and include safety locks to prevent accidental retraction on the ground. The landing gear ensures safe ground handling, takeoffs, and landings, while contributing to aerodynamic efficiency during flight."
      },
      {
        "name": "Powerplant Installation",
        "description": "TThe Diamond DA62 is powered by two Austro AE330 diesel engines, mounted in nacelles on the wings near the fuselage. The engine installation includes reinforced mounting points, cowling, and propeller hubs. This structure ensures the engines remain secure, transmit thrust efficiently, and minimize vibration. Airflow is directed through cooling ducts to maintain engine temperature, while structural reinforcements protect the fuselage and cockpit. The engines are integrated with full monitoring systems, transmitting data to cockpit displays for fuel, temperature, RPM, and system performance. Redundant systems ensure safety in case of engine failure. Proper installation is critical for thrust generation, vibration management, safety, and overall aircraft performance."
      }
    ]
  },
  {
    "name": "Airbus A320",
    "image": "https://aviationinteractivelearningplatform.netlify.app/images/aircrafts/A320.png",
    "description": "The Airbus A320 is a narrow‑body, short‑ to medium‑haul commercial jet that revolutionized airline operations with its introduction of full fly‑by‑wire controls. First entering service in the late 1980s, the A320 family has become one of the most successful aircraft programs in aviation history. The aircraft typically seats between 150 and 180 passengers and is powered by either CFM International or Pratt & Whitney engines. A key innovation is the side‑stick controller and flight envelope protection system, which enhances safety by preventing pilots from exceeding aircraft limits. The A320 is known for its fuel efficiency, operational flexibility, and commonality across the A320 family, reducing pilot training and maintenance costs. Modern variants feature advanced avionics, wingtip sharklets, and improved engines for lower fuel burn and emissions. The A320 operates globally on thousands of routes, serving as a backbone of many airline fleets.",
    "parts": [
      {
        "name": "Cockpit",
        "description": "The cockpit of the Airbus A320 is a highly advanced flight deck designed for two pilots operating modern commercial flights. It features side-by-side seating with ergonomically arranged controls including side-stick controllers, rudder pedals, throttle levers, and integrated autopilot and flight management systems. The cockpit employs a fly-by-wire system, where pilot inputs are converted into electronic signals that control the aircraft’s control surfaces, improving precision and safety. Large digital displays (Primary Flight Display and Navigation Display) provide real-time information on airspeed, altitude, attitude, engine performance, and navigation. Redundant systems ensure that failures do not compromise control. The cockpit is also pressurized and equipped with environmental control systems for pilot comfort during high-altitude flight. Ergonomic design reduces fatigue on long flights, while the layout allows easy access to critical flight controls and emergency procedures."
      },
      {
        "name": "Wings",
        "description": "The Airbus A320 features low-mounted, swept wings designed for efficient lift and fuel performance. Each wing houses high-lift devices such as slats and flaps to increase lift during takeoff and landing. Ailerons at the trailing edge control roll, while spoilers assist in descent and braking. The wings contain integral fuel tanks that contribute to the aircraft’s center of gravity management. Wing structure comprises spars, ribs, and skins that distribute aerodynamic and landing loads to the fuselage. Wingtip fences or sharklets reduce induced drag, improving fuel efficiency and range. The wings are aerodynamically optimized to provide stability, control, and smooth airflow under varying flight conditions. They are a crucial component for lift generation, maneuverability, and operational efficiency in commercial operations."
      },
      {
        "name": "Fuselage",
        "description": "The fuselage of the A320 is a cylindrical, semi-monocoque structure constructed from aluminum alloys and composites to balance strength and weight. It serves as the main body connecting wings, tail, landing gear, and engines. The fuselage houses the cockpit, passenger cabin, cargo compartments, and aircraft systems such as electrical wiring, hydraulics, and fuel lines. It is pressurized to maintain safe cabin conditions at cruising altitudes and reinforced to withstand aerodynamic loads and landing forces. Stringers, frames, and skin panels distribute stresses evenly, while aerodynamic shaping reduces drag for fuel efficiency. The fuselage also provides structural attachment points for emergency exits, doors, and interior furnishings. Its robust design ensures passenger safety and structural integrity during turbulence, takeoffs, landings, and high-speed flight, making it the backbone of the aircraft."
      },
      {
        "name": "Empennage (Tail Section)",
        "description": "TThe A320’s empennage includes a vertical stabilizer (fin), rudder, horizontal stabilizer, and elevators. The vertical stabilizer maintains directional stability, while the rudder provides yaw control during turns and crosswind operations. The horizontal stabilizer balances the aircraft longitudinally, while elevators control pitch for climbs, descents, and trimming. The tail surfaces are constructed with aluminum and composite materials to reduce weight and improve aerodynamic efficiency. Fly-by-wire actuators control the rudder and elevators based on pilot input, providing precise, stable responses. The empennage also supports aerodynamic balance, reducing pilot workload and ensuring predictable handling, even at high speeds or during turbulence. It is essential for safe, controlled flight throughout all phases of operation."
      },
      {
        "name": "Landing Gear",
        "description": "The A320 uses a retractable tricycle landing gear system with two main landing gear assemblies and a steerable nose gear. The main gear supports the aircraft during taxi, takeoff, and landing and absorbs impact forces through oleo-pneumatic shock struts. The nose gear provides steering control on the ground and also includes shock absorption. Retractable design reduces drag during flight. The landing gear is hydraulically actuated and equipped with safety interlocks to prevent accidental retraction on the ground. Its design supports the aircraft’s maximum takeoff and landing weight, ensuring operational safety and stability on runways. Regular maintenance and inspection ensure reliability in high-cycle commercial operations."
      },
      {
        "name": "Engine Nacelles / Powerplant Installation",
        "description": "The A320 is typically powered by two high-bypass turbofan engines mounted on pylons under the wings. The engine nacelles are reinforced to securely hold the engines while minimizing vibrations. Airflow management, cooling, and thrust transmission are optimized through nacelle design. Engines are integrated with fuel, hydraulic, and electronic control systems to monitor performance in real time. The installation ensures efficient propulsion, redundancy, and safety, allowing the aircraft to maintain long-range flight even if one engine fails. Proper nacelle design reduces drag, improves fuel efficiency, and ensures structural integrity."
      }
    ]
  },
  {
    "name": "Airbus A350",
    "image": "https://aviationinteractivelearningplatform.netlify.app/images/aircrafts/A350.png",
    "description": "The Airbus A350 XWB is a long‑range, wide‑body aircraft designed for efficiency, comfort, and environmental performance. Constructed largely from carbon‑fiber‑reinforced polymer, the A350 features a lightweight yet strong structure that reduces fuel burn and maintenance requirements. It is powered by Rolls‑Royce Trent XWB engines, among the most efficient large turbofan engines ever produced. The aircraft typically seats 300–350 passengers and offers ultra‑long‑haul capability. Advanced aerodynamics, including curved winglets and optimized wing design, contribute to exceptional performance. The A350 also emphasizes passenger comfort with a wider cabin, higher humidity, and lower cabin altitude. Airlines value the A350 for its operating economics, reliability, and ability to replace older wide‑body aircraft on long‑haul routes.",
    "parts": [
      {
        "name": "Cockpit",
        "description": "The Airbus A350 cockpit is a highly advanced flight deck designed for two pilots in long-haul commercial operations. It features side-by-side seating with ergonomically placed controls, including side-stick controllers, rudder pedals, throttle quadrants, and integrated autopilot and flight management systems. The cockpit employs fly-by-wire technology, where pilot inputs are transmitted electronically to control surfaces, enhancing precision, safety, and handling. Large glass displays provide real-time data on airspeed, altitude, attitude, navigation, engine performance, and aircraft systems. The design includes redundancy for all critical systems, ensuring continued operation in the event of component failure. Visibility is optimized for takeoff, approach, and landing operations. The cockpit is pressurized, climate-controlled, and ergonomically designed to reduce fatigue during long-duration flights. It also houses communication, navigation, and monitoring systems for situational awareness."
      },
      {
        "name": "Wings",
        "description": "The Airbus A350 features highly efficient, composite swept wings designed for long-range, fuel-efficient flight. The wings include high-lift devices like slats and flaps to enhance lift during takeoff and landing. Ailerons and spoilers allow precise roll control and speed management. The wings house integral fuel tanks that optimize aircraft balance and center of gravity. Wing design incorporates raked wingtips, reducing induced drag and improving range and fuel efficiency. Internal spars and ribs provide structural reinforcement, transferring aerodynamic loads to the fuselage. The wings’ aerodynamic shaping ensures smooth airflow, stability, and predictable handling at varying speeds and altitudes. They are essential for lift generation, efficient cruising, and operational safety in commercial aviation."
      },
      {
        "name": "Empennage (Tail Section)",
        "description": "CThe A350 empennage consists of a horizontal stabilizer, elevators, vertical stabilizer, and rudder, providing longitudinal and directional stability. The horizontal stabilizer maintains pitch balance, while the elevators control ascent, descent, and trim. The vertical stabilizer ensures yaw stability, and the rudder allows directional control during turns and crosswind operations. Constructed from composites, the empennage is lightweight, strong, and aerodynamically optimized. Fly-by-wire actuators manage control surfaces, ensuring precise, smooth handling and reducing pilot workload. The tail section is vital for safe, stable flight, particularly during takeoff, landing, turbulence, or emergency maneuvers."
      },
      {
        "name": "Fuselage",
        "description": "The A350 fuselage is a wide-body, semi-monocoque structure primarily constructed from carbon-fiber reinforced polymer composites. This material provides high strength, low weight, and resistance to corrosion, reducing maintenance requirements. The fuselage houses the cockpit, passenger cabin, cargo compartments, and integrated systems such as wiring, hydraulics, and environmental control. It serves as the structural backbone, connecting the wings, tail, landing gear, and engine pylons. Internal frames, stringers, and skin panels distribute aerodynamic and landing loads efficiently. The fuselage is pressurized for passenger comfort at high altitudes, and aerodynamic shaping reduces drag to improve fuel efficiency. Reinforced areas provide structural integrity during takeoffs, landings, and turbulence. The fuselage also supports interior fittings such as seating, galleys, and emergency exits, making it crucial for both structural strength and passenger safety."
      },
      {
        "name": "Landing Gear",
        "description": "The A350 uses a retractable tricycle landing gear system, including two main landing gear assemblies with multiple wheels per leg and a steerable nose gear. The main gear absorbs landing loads and supports the aircraft’s substantial weight on the ground. Shock-absorbing struts reduce impact forces during touchdown. The nose gear provides directional control while taxiing. Retractable design reduces drag during cruise, and hydraulic actuation ensures smooth operation. Safety mechanisms prevent accidental retraction on the ground. The landing gear is engineered to support high-frequency operations, long runways, and maximum takeoff and landing weights, making it a critical component for ground stability and safety."
      },
      {
        "name": "Engine Nacelles / Powerplant Installation",
        "description": "The A350 is powered by two high-bypass turbofan engines mounted on reinforced pylons beneath the wings. The nacelles secure the engines while minimizing vibrations and aerodynamic drag. Airflow management within the nacelle optimizes cooling, thrust, and fuel efficiency. Engines are fully integrated with electronic controls that monitor performance, fuel consumption, and health status. Redundant systems ensure that if one engine fails, the aircraft can safely continue flight. The nacelle and mounting structure are designed to withstand aerodynamic loads, engine torque, and operational stress, making it essential for propulsion, performance, and safety in long-range commercial operations."
      }
    ]
  },
  {
    "name": "Airbus A380",
    "image": "https://aviationinteractivelearningplatform.netlify.app/images/aircrafts/A380.png",
    "description": "The Airbus A380 is the world’s largest passenger aircraft, designed to handle high‑capacity, long‑haul routes between major hubs. Featuring a full double‑deck configuration, the A380 can carry more than 500 passengers in typical airline layouts. It is powered by four turbofan engines and incorporates advanced aerodynamics and materials to manage its immense size efficiently. The aircraft offers exceptional passenger comfort, with spacious cabins, reduced noise levels, and smooth ride quality. Airlines have used the A380 to maximize capacity at congested airports. Although production has ended, the A380 remains an engineering landmark and continues to operate on high‑demand routes.",
    "parts": [
      {
        "name": "Cockpit",
        "description": "The Airbus A380 cockpit is a state-of-the-art flight deck designed for two pilots in a wide-body, long-haul commercial aircraft. It features side-by-side seating, ergonomically arranged controls, and fly-by-wire technology, allowing precise control of the massive aircraft through electronic signals instead of mechanical linkages. The cockpit includes side-stick controllers, rudder pedals, throttle quadrants, and integrated autopilot and flight management systems. Large multi-function displays provide real-time information on airspeed, altitude, attitude, navigation, engine performance, and aircraft systems. Redundant systems ensure operational safety in case of component failures. The cockpit is pressurized, climate-controlled, and equipped with noise-reducing structures to maintain pilot comfort during long flights. Communication and navigation systems are integrated, enabling the crew to manage complex air traffic environments efficiently."
      },
      {
        "name": "Wings",
        "description": "The Airbus A380 features swept, high-aspect-ratio wings made primarily from composites and aluminum alloys. Each wing incorporates high-lift devices, such as slats, flaps, and spoilers, for enhanced takeoff and landing performance. The wings contain fuel tanks that contribute to center-of-gravity management and extended range capability. Ailerons and spoilers allow precise roll control, while winglets reduce induced drag and improve fuel efficiency. The wing structure is reinforced with multiple spars, ribs, and skins to withstand aerodynamic loads and weight distribution during flight. Its massive wingspan generates the lift necessary to carry up to 850 passengers in maximum configuration. The aerodynamic design ensures stable, efficient cruising at high altitudes while maintaining responsive handling characteristics. Overall, the wings are crucial for lift generation, aerodynamic efficiency, and long-range operational capability in the world’s largest passenger aircraft."
      },
      {
        "name": "Fuselage",
        "description": "The fuselage of the A380 is a double-deck, semi-monocoque structure made from a combination of aluminum alloys, titanium, and composites. It acts as the main structural backbone connecting wings, tail, landing gear, and engines. The fuselage houses the cockpit, two passenger decks, cargo compartments, and multiple internal systems such as wiring, hydraulics, and environmental controls. Its structure is reinforced to handle the enormous aerodynamic forces, pressurization loads, and stresses from takeoffs and landings. Stringers, frames, and skin panels distribute loads efficiently, maintaining integrity under high-stress conditions. Aerodynamic shaping reduces drag while supporting efficient lift distribution. Reinforcements around doors, windows, and structural joints ensure passenger safety. The fuselage also integrates the aircraft’s systems, including emergency exits, lighting, and cabin pressurization, making it vital for both structural strength and passenger safety on long-haul flights."
      },
      {
        "name": "Empennage (Tail Section)",
        "description": "The A380’s empennage includes a horizontal stabilizer, elevators, vertical stabilizer, and rudder, constructed from composite and aluminum materials for strength and lightweight efficiency. The horizontal stabilizer maintains longitudinal balance, while elevators control pitch for climbing, descending, and trimming. The vertical stabilizer ensures directional stability, while the rudder enables yaw control during turns, crosswinds, and asymmetric thrust conditions. Fly-by-wire actuators control these surfaces with high precision, reducing pilot workload. The tail section provides stability during turbulence and ensures predictable handling during all flight phases. Its design also minimizes aerodynamic drag while maximizing control effectiveness. The empennage is essential for safe flight, control, and balance, particularly in an aircraft of the A380’s size and mass."
      },
      {
        "name": "Landing Gear",
        "description": "The A380 uses an advanced retractable landing gear system with five sets of gear assemblies, including two nose wheels and three main gear assemblies, each with multiple wheels. The landing gear is designed to support the aircraft’s enormous maximum takeoff weight, absorb landing loads, and ensure stability during taxi, takeoff, and landing. Shock-absorbing oleo-pneumatic struts reduce impact forces, protecting the airframe and providing passenger comfort. The nose gear provides precise steering on the ground, while main gears carry most of the aircraft’s weight. Hydraulic systems actuate extension and retraction, and safety interlocks prevent accidental deployment or retraction. The landing gear is critical for ground stability, safe operations, and efficient movement on runways at airports worldwide."
      },
      {
        "name": "Engine Nacelles / Powerplant Installation",
        "description": "TThe A380 is powered by four high-bypass turbofan engines mounted on reinforced pylons under the wings. The nacelles secure the engines, control airflow for thrust and cooling, and reduce vibration and aerodynamic drag. Engines are fully integrated with electronic monitoring systems to manage fuel, performance, and health status in real time. Redundant safety systems allow continued operation in case of engine failure. The nacelle and pylon structure are designed to withstand aerodynamic loads, engine torque, and operational stress, ensuring efficient propulsion, optimal fuel efficiency, and safe long-range operation. The engines provide the necessary thrust to lift one of the world’s largest passenger aircraft safely and efficiently."
      }
    ]
  },
  {
    "name": "Boeing 737",
    "image": "https://aviationinteractivelearningplatform.netlify.app/images/aircrafts/b737.png",
    "description": "The Boeing 737 is one of the most successful and widely used narrow-body commercial aircraft in aviation history. Designed primarily for short- to medium-haul routes, it is operated by airlines all over the world due to its reliability, efficiency, and versatility. First introduced in the late 1960s, the 737 has evolved through multiple generations, including the Classic, Next Generation (NG), and the latest 737 MAX series. The aircraft typically accommodates between 130 and 190 passengers depending on configuration. It is powered by two turbofan engines mounted under low-mounted wings, allowing easy ground access for maintenance. The 737 is known for its strong performance on short runways, making it suitable for operations at smaller and regional airports. Modern variants feature advanced avionics, digital flight displays, and improved aerodynamics with winglets to reduce fuel consumption. Airlines benefit from cockpit commonality across variants, reducing pilot training costs. The aircraft’s durable structure and efficient turnaround times make it ideal for high-frequency operations. Overall, the Boeing 737 continues to be a backbone of global airline fleets, offering a balance of performance, operating economy, and proven design.",
    "parts": [
      {
        "name": "Cockpit",
        "description": "The Boeing 737 cockpit is designed for two pilots and is a modern, ergonomically arranged flight deck. It features side-by-side seating with easy access to all primary controls, including yokes, rudder pedals, throttle quadrants, autopilot systems, and communication instruments. Modern variants utilize digital avionics (glass cockpit), integrating Primary Flight Displays (PFD), Navigation Displays (ND), engine monitoring, and aircraft system information into multifunction screens. The cockpit employs a combination of manual and electronic flight control systems, giving pilots precision and safety during flight. It is pressurized, climate-controlled, and designed for long-haul comfort and efficiency. Visibility is optimized for takeoff, landing, and taxi operations. Redundant systems, alarms, and safety interlocks enhance operational reliability. The cockpit serves as the aircraft’s operational hub, allowing pilots to monitor flight parameters, navigate complex airspace."
      },
      {
        "name": "Fuselage",
        "description": "The fuselage of the Boeing 737 is a semi-monocoque aluminum structure forming the main body of the aircraft. It connects wings, tail, landing gear, and engines, acting as the structural backbone. The fuselage houses the cockpit, passenger cabin, cargo compartments, and all essential systems, including electrical wiring, hydraulics, and environmental controls. It is pressurized to maintain a safe and comfortable cabin environment at cruising altitudes. The fuselage is designed to handle aerodynamic forces, landing stresses, and pressurization loads. Frames, stringers, and skin panels evenly distribute stresses and provide rigidity while maintaining a relatively low weight. Reinforced sections support doors, emergency exits, and seating attachments. Aerodynamically shaped, it minimizes drag while maintaining strength and durability. The fuselage is vital for structural integrity, passenger safety, and balanced aircraft operation."
      },
      {
        "name": "Wings",
        "description": "The Boeing 737 features low-mounted, swept wings made from aluminum alloys designed for lift, efficiency, and stability. Each wing houses fuel tanks and integrates control surfaces including ailerons, flaps, and spoilers. Ailerons control roll, flaps increase lift during takeoff and landing, and spoilers assist in speed reduction and descent control. Wing spars and ribs transfer aerodynamic loads to the fuselage, ensuring structural stability. Winglets or blended wingtips reduce induced drag, improving fuel efficiency and range. The aerodynamic shape provides stability at cruising speeds, reduces turbulence effects, and ensures smooth handling for pilots. The wings are crucial for lift generation, flight control, and maintaining balance throughout all phases of flight."
      },
      {
        "name": "Empennage (Tail Section)",
        "description": "The 737 empennage consists of a horizontal stabilizer, elevators, vertical stabilizer, and rudder. The horizontal stabilizer maintains longitudinal balance, while the elevators control pitch for climbs, descents, and trimming. The vertical stabilizer ensures yaw stability, and the rudder allows directional control during turns and crosswind landings. Constructed from aluminum, the tail section is aerodynamically optimized to reduce drag while maintaining strength. Control surfaces are connected to cockpit controls through mechanical linkages or cables in older variants and partially electronic systems in newer ones. The empennage is essential for stability, controllability, and safe maneuvering during all flight conditions."
      },
      {
        "name": "Landing Gear",
        "description": "The Boeing 737 uses a retractable tricycle landing gear system. It consists of two main gear assemblies and a steerable nose gear. The main gear absorbs landing loads and supports the aircraft’s weight on the ground. Shock-absorbing struts reduce impact forces, protecting the fuselage and passengers. The nose gear provides precise steering during taxiing and is designed to handle high-speed ground operations. The landing gear is hydraulically actuated, with safety locks preventing accidental retraction on the ground. Its design supports repeated high-cycle commercial operations and ensures stability during takeoff, landing, and taxi maneuvers."
      },
      {
        "name": "Engine Nacelles / Powerplant Installation",
        "description": "The Boeing 737 is powered by two high-bypass turbofan engines mounted under the wings on reinforced pylons. The nacelles secure the engines, streamline airflow, and reduce drag while absorbing vibration and thrust forces. Engines are integrated with electronic control systems for monitoring fuel, thrust, temperature, and overall performance. Redundant systems ensure continued operation in case of engine failure. The structural mounting distributes loads to the wing and fuselage while ensuring stability and safety. Engine installation is critical for propulsion, efficiency, and operational reliability in commercial operations."
      }
    ]
  },
  {
    "name": "Boeing 787 Dreamliner",
    "image": "https://aviationinteractivelearningplatform.netlify.app/images/aircrafts/b787.png",
    "description": "The Boeing 787 Dreamliner is a modern wide-body aircraft designed for long-haul, fuel-efficient operations and enhanced passenger comfort. It represents a major technological advancement in commercial aviation, with extensive use of composite materials that make up more than half of the aircraft’s structure. These materials reduce weight, improve fuel efficiency, and minimize corrosion. The 787 typically carries between 240 and 330 passengers and enables airlines to operate long-distance, point-to-point routes that were previously uneconomical. It is powered by advanced turbofan engines, such as the Rolls-Royce Trent 1000 or General Electric GEnx, which provide lower fuel burn and reduced noise levels. The aircraft features highly efficient aerodynamics, including raked wingtips, which reduce drag and improve range. Inside the cabin, the Dreamliner offers larger windows, improved air quality, higher humidity, and lower cabin altitude, enhancing passenger comfort on long flights. The 787 also uses advanced electrical systems instead of traditional pneumatic systems, increasing overall efficiency. Due to its lower operating costs and flexibility, the Boeing 787 has become a popular choice for airlines operating long-haul and medium-capacity routes.",
    "parts": [
      {
        "name": "Cockpit",
        "description": "The Boeing 787 cockpit is a modern, two-pilot flight deck designed for long-haul operations and high efficiency. It features side-by-side seating with ergonomically placed side-stick or yoke controls, rudder pedals, throttle quadrants, and an integrated autopilot and flight management system. The cockpit uses advanced glass displays, including Primary Flight Displays (PFD) and Multi-Function Displays (MFD), showing airspeed, altitude, attitude, navigation, engine performance, and aircraft systems. The 787 employs fly-by-wire technology, converting pilot inputs into electronic commands for precise control of the aircraft’s surfaces. Redundant systems ensure safety in case of component failure. Visibility is excellent for takeoffs, approaches, and landings, while pressurization, climate control, and noise insulation enhance pilot comfort on long flights. The cockpit integrates communication, navigation, and monitoring systems, serving as the operational hub."
      },
      {
        "name": "Fuselage",
        "description": "The Boeing 787 fuselage is a wide-body, semi-monocoque structure primarily constructed from carbon-fiber reinforced polymer composites, providing high strength, reduced weight, and corrosion resistance. It acts as the central backbone, connecting wings, tail, landing gear, and engine pylons. The fuselage houses the cockpit, passenger cabin, cargo holds, and integrated systems such as electrical, hydraulic, and environmental controls. Its composite design allows pressurization at lower cabin altitude, enhancing passenger comfort. Internal frames, stringers, and skin panels evenly distribute aerodynamic and landing loads. Reinforced areas provide structural integrity around doors, windows, and emergency exits. Aerodynamic shaping reduces drag, improving fuel efficiency and range. The fuselage also supports seating, galleys, lavatories, and emergency systems, making it critical for structural strength, operational efficiency, and passenger safety on long-range flights."
      },
      {
        "name": "Wings",
        "description": "The Boeing 787 features swept, composite wings designed for long-range efficiency and reduced fuel consumption. High-lift devices, including leading-edge slats and trailing-edge flaps, enhance lift during takeoff and landing. Ailerons and spoilers provide roll control and descent management. The wings contain integral fuel tanks to optimize center-of-gravity and long-range operations. Their flexible, composite construction reduces weight while allowing slight bending to absorb turbulence forces, improving aerodynamic efficiency and passenger comfort. Winglets reduce induced drag and enhance fuel efficiency. Internal spars and ribs distribute aerodynamic loads to the fuselage. The wings are essential for lift, stability, and overall performance, allowing the 787 to cruise efficiently at high altitudes and speeds over extended distances."
      },
      {
        "name": "Empennage (Tail Section)",
        "description": "The 787’s empennage includes the horizontal stabilizer, elevators, vertical stabilizer, and rudder. The horizontal stabilizer balances the aircraft longitudinally, while the elevators control pitch for climbs, descents, and trim. The vertical stabilizer provides directional stability, and the rudder enables yaw control during turns and crosswinds. Tail surfaces are constructed from composites for strength and lightweight efficiency. Fly-by-wire actuators precisely manage control surfaces, reducing pilot workload and ensuring safe, predictable handling. The empennage stabilizes the aircraft, particularly during turbulence, asymmetric thrust, or emergency maneuvers, making it indispensable for controlled flight and aerodynamic balance."
      },
      {
        "name": "Landing Gear",
        "description": "The Boeing 787 uses a retractable tricycle landing gear system, including two main landing gear assemblies and a steerable nose gear. Main gear assemblies are equipped with multiple wheels to support the aircraft’s substantial maximum takeoff weight and absorb landing loads. Shock-absorbing struts reduce impact forces, protecting the fuselage and providing smoother landings. The nose gear allows precise steering on taxiways and runways. Hydraulic actuation ensures smooth extension and retraction, with safety interlocks preventing accidental gear operation on the ground. The landing gear is critical for ground stability, safe takeoffs, and landings, and is engineered to withstand high-cycle commercial operations."
      },
      {
        "name": "Engine Nacelles / Powerplant Installation",
        "description": "The Boeing 787 is powered by two high-bypass turbofan engines mounted on reinforced pylons under the wings. The nacelles secure the engines while reducing aerodynamic drag and vibration. They incorporate airflow channels to optimize cooling and thrust efficiency. Engine monitoring systems continuously provide data on fuel consumption, temperature, and RPM to the cockpit. Redundant systems ensure safe operation in case of engine failure. Structural reinforcements transmit thrust and loads to the wings and fuselage. Proper installation ensures efficient propulsion, reliability, and safety during long-haul operations, making the engine system a critical component of aircraft performance and operational capability."
      }
    ]
  },
  {
    "name": "Boeing 777",
    "image": "https://aviationinteractivelearningplatform.netlify.app/images/aircrafts/b777.png",
    "description": "The Boeing 777 is a long-range, wide-body twin-engine aircraft developed to meet the demands of high-capacity international travel. Known for its reliability and performance, the 777 is widely used on long-haul routes across continents. It typically seats between 300 and 400 passengers, depending on the configuration. One of its most notable features is its powerful turbofan engines, among the largest and most powerful jet engines ever produced, allowing the aircraft to achieve exceptional range and payload capability. The 777 was one of the first commercial aircraft to be designed entirely using computer-aided design (CAD), improving accuracy and efficiency in manufacturing. It features advanced avionics, fly-by-wire assistance, and sophisticated flight management systems that enhance safety and reduce pilot workload. The aircraft’s large wings are optimized for long-distance efficiency, providing excellent lift and fuel economy. With strong structural design and proven ETOPS capability, the Boeing 777 can safely operate long overwater routes with only two engines. Airlines value the 777 for its durability, passenger comfort, and ability to operate on some of the world’s longest routes, making it a cornerstone of global long-haul aviation.",
    "parts": [
      {
        "name": "Cockpit",
        "description": "The Boeing 777 cockpit is a modern, wide-body flight deck designed for two pilots operating long-haul commercial flights. It features side-by-side seating with ergonomically arranged controls including yokes, rudder pedals, throttle quadrants, and integrated autopilot and flight management systems. The cockpit uses digital glass displays, providing real-time information on airspeed, altitude, attitude, engine performance, navigation, and aircraft systems. Fly-by-wire systems enhance precision and reduce pilot workload, while redundant systems ensure continued operation in case of component failure. Visibility is optimized for takeoffs, landings, and taxiing. The cockpit is pressurized, climate-controlled, and ergonomically designed to reduce fatigue during extended flights. Communication, navigation, and monitoring systems are fully integrated, allowing pilots to maintain situational awareness and manage the aircraft efficiently."
      },
      {
        "name": "Fuselage",
        "description": "The Boeing 777 fuselage is a wide-body, semi-monocoque structure made primarily from aluminum alloys and composites. It forms the aircraft’s main body, connecting wings, tail, landing gear, and engine pylons. The fuselage houses the cockpit, passenger cabin, cargo holds, and all critical systems such as electrical wiring, hydraulics, and environmental controls. It is pressurized to maintain safe and comfortable conditions at high altitudes. Internal frames, stringers, and skin panels distribute aerodynamic loads and landing stresses evenly, providing structural integrity and durability. Reinforced sections around doors, windows, and seating attachments support passenger safety. The aerodynamic shape reduces drag and improves fuel efficiency while accommodating two passenger decks in certain configurations. The fuselage is essential for structural strength, passenger safety, and overall aircraft stability during flight."
      },
      {
        "name": "Wings",
        "description": "The Boeing 777 features large, swept wings constructed from aluminum alloys and composites, optimized for long-range performance and efficiency. The wings include high-lift devices such as slats and flaps to increase lift during takeoff and landing. Ailerons provide roll control, while spoilers assist in descent and speed management. The wings house integral fuel tanks, contributing to balance and center-of-gravity management for extended-range operations. Winglets reduce induced drag and improve fuel efficiency. Internal spars and ribs distribute aerodynamic loads to the fuselage and enhance structural stability. The wings are crucial for generating lift, maintaining flight stability, and ensuring efficient operation during long-haul flights. Their design also accommodates high-thrust engines, allowing the 777 to achieve its maximum takeoff weight and range."
      },
      {
        "name": "Empennage (Tail Section)",
        "description": "The Boeing 777’s empennage consists of a horizontal stabilizer, elevators, vertical stabilizer, and rudder, constructed from lightweight composites and aluminum alloys. The horizontal stabilizer balances the aircraft longitudinally, while elevators control pitch for climbs, descents, and trimming. The vertical stabilizer ensures directional stability, and the rudder provides yaw control during turns, crosswinds, and asymmetric thrust scenarios. Fly-by-wire actuators precisely manage control surfaces, reducing pilot workload and ensuring predictable responses. The tail section stabilizes the aircraft under turbulence, heavy load conditions, and emergency maneuvers. It is also aerodynamically shaped to minimize drag while maintaining maximum control effectiveness. The empennage is critical for maintaining safe, stable, and controllable flight."
      },
      {
        "name": "Landing Gear",
        "description": "The Boeing 777 uses a retractable tricycle landing gear system with two main gear assemblies and a steerable nose gear. Each main gear has multiple wheels to support the aircraft’s maximum takeoff weight and absorb landing impacts. Shock-absorbing struts reduce stress on the airframe and provide passenger comfort. The nose gear provides steering capability during taxi and ground operations. Hydraulic systems actuate gear extension and retraction, while safety interlocks prevent accidental deployment or retraction. The landing gear is engineered to handle high-cycle commercial operations, long runways, and heavy loads, ensuring stability and safety during all ground and flight phases."
      },
      {
        "name": "Engine Nacelles / Powerplant Installation",
        "description": "The Boeing 777 is powered by two high-bypass turbofan engines, mounted on reinforced pylons under the wings. The nacelles secure the engines while controlling airflow, reducing drag, and minimizing vibration. Engine monitoring systems continuously provide data on fuel, temperature, RPM, and thrust to the cockpit. Redundant safety and electronic systems ensure reliable operation even in the event of engine failure. Structural reinforcements transmit thrust and loads safely to the wings and fuselage. Proper installation is critical for propulsion, efficiency, and safe operation, allowing the aircraft to fly long-range international routes with heavy payloads."
      }
    ]
  },
  {
    "name": "Boeing 747",
    "image": "https://aviationinteractivelearningplatform.netlify.app/images/aircrafts/b747.png",
    "description": "The Boeing 747, famously known as the “Queen of the Skies,” is one of the most iconic aircraft in aviation history. Recognized by its distinctive hump-backed upper deck, the 747 was the world’s first wide-body jumbo jet and revolutionized long-distance air travel when it entered service in the early 1970s. Designed for high-capacity, long-haul routes, the aircraft can carry more than 400 passengers in typical airline configurations. It is powered by four turbofan engines, providing the thrust required for heavy payloads and intercontinental flights. The upper deck was originally intended for first-class seating but later enabled the aircraft’s conversion into a highly efficient cargo platform. The 747 features a strong swept-wing design that supports its large weight while maintaining stable cruise performance. Over the decades, multiple variants were developed, including passenger, cargo, and military versions. Although newer twin-engine aircraft have replaced it on many routes due to improved fuel efficiency, the Boeing 747 remains an engineering milestone. Its contribution to global connectivity, cargo transport, and aviation history ensures its lasting legacy even as it gradually retires from passenger service.",
    "parts": [
      {
        "name": "Cockpit",
        "description": "The Boeing 747 cockpit is a spacious, two-pilot flight deck designed for long-haul operations with advanced avionics and flight management systems. Side-by-side seating provides ergonomic access to controls, including yokes, rudder pedals, throttle quadrants, autopilot, and integrated navigation and communication systems. Modern variants use glass cockpit displays with Primary Flight Displays (PFD), Multi-Function Displays (MFD), and engine monitoring screens, providing real-time information on airspeed, altitude, attitude, navigation, and aircraft systems. Fly-by-wire systems in later models enhance control precision, while redundant systems ensure continued operation during failures. The cockpit is pressurized, climate-controlled, and noise-insulated, improving pilot comfort during extended flights. Visibility is optimized for takeoffs, landings, and taxiing. It serves as the operational hub of the aircraft, allowing pilots to safely monitor and control all flight parameters."
      },
      {
        "name": "Fuselage",
        "description": "The Boeing 747 fuselage is a double-deck, semi-monocoque structure primarily constructed from aluminum alloys and composites for strength and durability. It serves as the central body connecting wings, tail, landing gear, and engine pylons. The fuselage houses the cockpit, passenger decks, cargo holds, and integrated systems such as wiring, hydraulics, and environmental controls. Reinforced frames, stringers, and skin panels distribute aerodynamic and landing stresses evenly. Pressurization maintains a safe and comfortable environment for passengers at high altitudes. Aerodynamic shaping reduces drag and improves fuel efficiency. Reinforced areas around doors, emergency exits, and seating attachments enhance passenger safety. The fuselage is the backbone of the aircraft, providing structural integrity, passenger comfort, and stability for one of the largest capacity commercial airplanes ever built."
      },
      {
        "name": "Wings",
        "description": "The Boeing 747 has swept, high-aspect-ratio wings made from aluminum and composite materials, designed to support its massive weight and provide long-range efficiency. The wings contain fuel tanks that contribute to weight distribution and center-of-gravity management. High-lift devices such as leading-edge slats and trailing-edge flaps improve lift during takeoff and landing. Ailerons control roll, while spoilers assist in speed reduction and descent management. Winglets or raked wingtips reduce induced drag, increasing fuel efficiency. Internal spars and ribs provide structural support, distributing aerodynamic and engine loads to the fuselage. The wings generate the lift required for safe operation at maximum takeoff weight and contribute significantly to overall stability, handling, and aerodynamic efficiency for long-range flights."
      },
      {
        "name": "Empennage (Tail Section)",
        "description": "The 747’s empennage includes a horizontal stabilizer, elevators, vertical stabilizer, and rudder, constructed from aluminum and composite materials. The horizontal stabilizer maintains longitudinal balance, while elevators control pitch for climbing, descending, and trimming. The vertical stabilizer ensures directional stability, and the rudder enables yaw control, particularly during crosswind operations or asymmetric thrust scenarios. Control surfaces are connected to the cockpit through mechanical or electronic linkages. The empennage provides stability, balance, and precise maneuvering capability, especially critical for an aircraft of the 747’s size and weight. Aerodynamic shaping reduces drag while maximizing control efficiency, making the tail essential for safe flight and handling."
      },
      {
        "name": "Landing Gear",
        "description": "The Boeing 747 uses a retractable tricycle landing gear system consisting of four main gear assemblies and a steerable nose gear. The main gear is equipped with multiple wheels to support the aircraft’s immense maximum takeoff weight and absorb landing impact forces. Oleo-pneumatic shock struts reduce stress on the airframe and improve passenger comfort. The nose gear provides steering capability on taxiways and runways. Hydraulic systems control extension and retraction, with safety interlocks preventing accidental operation. The landing gear is engineered for high-cycle commercial operations, heavy payloads, and long runway operations, ensuring stability and safe takeoff and landing performance."
      },
      {
        "name": "Engine Nacelles / Powerplant Installation",
        "description": "The Boeing 747 is powered by four high-bypass turbofan engines, mounted on reinforced pylons beneath the wings. Engine nacelles provide structural support, reduce vibration, and optimize airflow for thrust and cooling. Engines are integrated with monitoring systems to track performance, fuel consumption, and health status. Redundant systems ensure continued operation in the event of a single engine failure. Structural pylons distribute engine loads safely to the wing and fuselage. Proper installation is critical for reliable propulsion, efficiency, and safety, enabling the 747 to transport hundreds of passengers and cargo across intercontinental distances."
      }
    ]
  }
]);

  console.log("✅ Aircraft data seeded successfully");
  } catch (err) {
    console.error("❌ Seeding error:", err);
  } finally {
    mongoose.disconnect();
  }
}

seedAircrafts();